name: Build and Publish eGeoffrey Package

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request: 
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

